INSERT INTO brands (id, brand_name) VALUES
    (1, 'Samsung'),
    (2, 'LG'),
    (3, 'Bosch'),
    (4, 'Sony'),
    (5, 'Apple'),
    (6, 'HP'),
    (7, 'Lenovo'),
    (8, 'Dyson'),
    (9, 'Philips'),
    (10, 'Panasonic'),
    (11, 'Whirlpool'),
    (12, 'Electrolux'),
    (13, 'Delonghi'),
    (14, 'Kenwood'),
    (15, 'Tefal'),
    (16, 'Miele'),
    (17, 'Xiaomi'),
    (18, 'Huawei'),
    (19, 'Acer'),
    (20, 'Asus'),
    (21, 'Sharp'),
    (22, 'JBL'),
    (23, 'Sennheiser'),
    (24, 'Bose'),
    (25, 'KitchenAid'),
    (26, 'Siemens'),
    (27, 'Fujitsu'),
    (28, 'Ariston'),
    (29, 'Hitachi'),
    (30, 'Candy'),
    (31, 'Haier'),
    (32, 'Hisense'),
    (33, 'Morphy Richards'),
    (34, 'Beko'),
    (35, 'Russell Hobbs'),
    (36, 'Gorenje'),
    (37, 'Nespresso'),
    (38, 'Krups'),
    (39, 'Breville'),
    (40, 'Logitech'),
    (41, 'Razer'),
    (42, 'MSI'),
    (43, 'Gigabyte'),
    (44, 'Dell'),
    (45, 'Microsoft'),
    (46, 'Epson'),
    (47, 'Canon'),
    (48, 'Brother'),
    (49, 'Zanussi'),
    (50, 'Toshiba');

ALTER TABLE brands AUTO_INCREMENT = 51;